Часть 15
AntonDementev/tutu pull request #1
Opened 2017-05-04 12:12 UTC by AntonDementev

2017-05-04 13:09 UTC, vkurennov requested changes

2017-05-04 13:09 UTC, vkurennov commented on app/views/trains/show.html.erb
> +waggons1_amount = 0
Никогда ничего не считай в видах, сделай методы в моделях и вызывай их отсюда

2017-05-04 15:46 UTC, vkurennov requested changes

2017-05-04 15:46 UTC, vkurennov commented on app/models/train.rb
> +  def update_values
Не очень удачное название. update в контексте моделей означает изменение данных в базе, ты же ничего не меняешь, а просто считаешь

2017-05-04 15:46 UTC, vkurennov commented on app/models/train.rb
> +      if waggon.category_id == 1
Слишком много дублирования. Сделай так, чтобы метод принимал тип вагона и возвращал данные только для него

2017-05-04 15:46 UTC, vkurennov commented on app/models/train.rb
> +  attr_reader :waggons1_amount, :waggon1_places_amount_top, :waggon1_places_amount_bot, :waggons2_amount, :waggon2_places_amount_top, :waggon2_places_amount_bot
Вот это зря, потому что эти методы не будут работать, если не вызвать метод update_values, т.е. слишком большая связанность методов.

2017-05-04 15:46 UTC, vkurennov commented on app/models/train.rb
> +      if waggon.category_id == 1
А возвращать можешь массив данных или хеш.

2017-05-05 13:14 UTC, webmstk commented on app/views/waggons/_form.html.erb
> +    <%= f.radio_button :category_id, 2 %>
Лучше значения хранить в константах

2017-05-05 17:21 UTC, vkurennov approved these changes

2017-05-07 09:57 UTC, merged