Часть 16
AntonDementev/tutu pull request #2
Opened 2017-05-11 23:34 UTC by AntonDementev

2017-05-12 07:12 UTC, vkurennov requested changes

2017-05-12 07:12 UTC, vkurennov commented on app/controllers/waggons_controller.rb
> +        format.html { redirect_to @waggon.becomes(Waggon), notice: 'Вагон был успешно создан.' }
1. Можно не писать формат и блок respond_to, если у тебя только один формат ответа
2. Можно было бы написать `redirect_to wagon_path(@wagon)`

2017-05-12 07:12 UTC, vkurennov commented on app/models/railway_station.rb
> +    set_number_in_route_by_id(route.id, number)
Можно все было бы сделать прямо в этом методе. Тут можно было бы и id использовать

2017-05-12 07:12 UTC, vkurennov commented on app/models/railway_station.rb
> +    railway_stations_routes.each do |statoin_route|
Перебор средставми руби долгий и не эффективный. Лучше было бы найти нужный объект через where

2017-05-12 07:12 UTC, vkurennov commented on app/models/railway_station.rb
> +        statoin_route.station_number_in_route = number
Можно использовать метод update, чтобы и присвоить значение и сохранить его сразу

2017-05-12 07:12 UTC, vkurennov commented on app/models/railway_station.rb
> +    railway_stations_routes.each do |statoin_route|
Используй where

2017-05-12 07:12 UTC, vkurennov commented on app/models/railway_station.rb
> +    number_in_route_id(route.id)
Лишний метод, можно все сделать в методе nubmer_in_route

2017-05-12 07:12 UTC, vkurennov commented on app/models/train.rb
> +  def places_amount(waggon_type, places_type)
Это нужно сделать средствами arel (where, sum и т.п.)

2017-05-12 07:12 UTC, vkurennov commented on app/models/waggon.rb
> +      self.number =  self.train.waggons.last.number + 1
Тут лучше не последний брать вагон (ведь нумерация может быть и с хвоста, тогда последний - это вагон с минимальным номером), а просто максимальное значение (метод maximum)

2017-05-12 07:12 UTC, vkurennov commented on app/views/trains/show.html.erb
> +    <li><%= link_to "#{waggon.number} (#{waggon.type})", waggon.becomes(Waggon) %></li>
Дублирование. Сделай у поезда метод, который сразу возвращает вагоны в нужном порядке и используй его

2017-05-12 07:12 UTC, vkurennov commented on app/views/waggons/_form.html.erb
> +    <%= f.radio_button :type, "CoupeWaggon" %> Купе
Тут лучше был бы выпаающий список

2017-05-12 07:12 UTC, vkurennov commented on app/views/waggons/show.html.erb
> +  <% case  @waggon.type  %>
Чтобы не использовать case, стоит применить принцип convention over configuration: сделай паршл для каждого типа вагона и назови его так, как называется тип вагона. Т.е. для `CoupeWaggon`, паршл `_coupe_waggon` и т.п. Используя метод underscore из названия типа легко получить название паршала и отрендерить нужный

2017-05-14 07:45 UTC, iBublik commented on app/models/waggon.rb
> +    if self.train.waggons.last.present?
Можно просто `self.number = train.wagons.count + 1`

2017-05-14 07:49 UTC, iBublik commented on app/views/waggons/show.html.erb
> +  <%= render ActiveSupport::Inflector.underscore(@waggon.type) %>
Rails вносит изменения в базовые классы, так что можно просто `@wagon.type.underscore`

2017-05-14 10:31 UTC, vkurennov approved these changes

2017-05-14 13:00 UTC, merged